### ISSUE TITLE
Status light flashes continuously

### ISSUE THREAD

**Issue by mincrmatt12** [tylertian123/TCalc#2]
I believe I have assembled it correctly, but the status light continuously flashes and key presses don't work.

**Comment by tylertian123** [comment]
Oh that's just the "random light show" feature. Totally not a bug at all. As for why the key presses don't work - during the "random light show" the keyboard is automatically disabled so that you can focus on the beauty of the lights instead of pressing buttons.

**Comment by mincrmatt12** [comment]
Is there an option to disable this "feature"? It is getting in the way due to the RNG being rather terrible at being random -- the light show often appears in long bursts.

**Comment by tylertian123** [comment]
Yes, you can disable Random Light Show by disconnecting the keyboard.

**Comment by mincrmatt12** [comment]
Sounds like a plan; resolving issue internally as "refused to fix"
